#!/usr/bin/env bash
# configure the Nginx server to listen on port 80. create a symbolic link (-s) between the Nginx configuration file and enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)" # terminate the first Nginx process id
